version: 2

sources:
  - name: raw
    database: plasma-minutia-402208
    schema: gz_raw_data
    description: greenweez data source
    tables:
      - name: sales
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        
        identifier: raw_gz_sales
        description: sales of greenweez
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for this order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: the product id
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product

      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: adwords of greenweez
        columns:
          - name: date_date
            description: the date of purchase
          - name: paid_source
            description: source of payment
          - name: campaign_key
            description: campaign code
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the ads
          - name: impression
            description: no idea
          - name: click
            description: number of clicks
            tests:
              - unique
              - not_null

      - name: bing
        identifier: raw_gz_bing
        description: bing for greenweez
        columns:
          - name: date_date
            description: the date of purchase
          - name: paid_source
            description: source of payment
          - name: campaign_key
            description: campaign code
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the ads
          - name: impression
            description: no idea
          - name: click
            description: number of clicks
            tests:
              - unique
              - not_null

      - name: criteo
        identifier: raw_gz_criteo
        description: criteo for greenweez
        columns:
          - name: date_date
            description: the date of purchase
          - name: paid_source
            description: source of payment
          - name: campaign_key
            description: campaign code
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the ads
          - name: impression
            description: no idea
          - name: click
            description: number of clicks
            tests:
              - unique
              - not_null

      - name: facebook
        identifier: raw_gz_facebook
        description: facebook for greenweez
        columns:
          - name: date_date
            description: the date of purchase
          - name: paid_source
            description: source of payment
          - name: campaign_key
            description: campaign code
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the ads
          - name: impression
            description: no idea
          - name: click
            description: number of clicks
            tests:
              - unique
              - not_null